-- ============================================================
-- GIAS / Education Provider Registry
-- Schema changes v0.1 (prototype / test migration)
-- File: 003-schema-v0.1-changes.sql
--
-- Assumptions:
--   * 001-baseline-schema-180626.sql has already run.
--   * Reference rows, except Section 41 and initial measure types,
--     will be loaded after extraction from the legacy database.
--   * This is an iterative v0.1 for local testing.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- 1. Reference tables
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ref.admissions_gender (
    admissions_gender_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ref.local_authority (
    local_authority_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    effective_from DATE,
    effective_to DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_local_authority_dates
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from)
);

-- Provisional terminology pending advice from the faiths team.
CREATE TABLE IF NOT EXISTS ref.religion (
    religion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ref.diocese (
    diocese_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    religion_id BIGINT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    effective_from DATE,
    effective_to DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_diocese_religion
        FOREIGN KEY (religion_id) REFERENCES ref.religion (religion_id),
    CONSTRAINT chk_diocese_dates
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from)
);

CREATE TABLE IF NOT EXISTS ref.religious_character (
    religious_character_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ref.religious_ethos (
    religious_ethos_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ref.nursery_provision (
    nursery_provision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ref.boarders (
    boarders_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ref.boarding_establishment_type (
    boarding_establishment_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ref.section41_approval_status (
    section41_approval_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    display_order INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ref.special_classes (
    special_classes_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ref.type_of_resourced_provision (
    type_of_resourced_provision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ref.provision_measure_type (
    provision_measure_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    unit TEXT NOT NULL,
    description TEXT,
    effective_from DATE,
    effective_to DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_provision_measure_type_dates
        CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from),
    CONSTRAINT chk_provision_measure_type_unit
        CHECK (unit IN ('COUNT', 'PERCENTAGE'))
);

-- ------------------------------------------------------------
-- 2. Confirmed / initial reference data
-- ------------------------------------------------------------

INSERT INTO ref.section41_approval_status (code, name, display_order, is_active)
VALUES
    ('1', 'Approved',       1, TRUE),
    ('2', 'Not approved',   2, TRUE),
    ('3', 'Not applicable', 3, TRUE)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    display_order = EXCLUDED.display_order,
    is_active = EXCLUDED.is_active;

INSERT INTO ref.provision_measure_type (code, name, unit, description, is_active)
VALUES
    ('TOTAL_PUPILS', 'Number of pupils', 'COUNT',
     'Total pupil count observed for an establishment at a stated date or reporting period.', TRUE),
    ('SCHOOL_CAPACITY', 'School capacity', 'COUNT',
     'Published school capacity observed for an establishment at a stated date or reporting period.', TRUE)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    unit = EXCLUDED.unit,
    description = EXCLUDED.description,
    is_active = EXCLUDED.is_active;

-- ------------------------------------------------------------
-- 3. Establishment: UKPRN and current diocese
-- ------------------------------------------------------------

ALTER TABLE core.establishment
    ADD COLUMN IF NOT EXISTS ukprn TEXT,
    ADD COLUMN IF NOT EXISTS diocese_id BIGINT;

-- Optional UKPRN uniqueness while allowing multiple NULL values.
CREATE UNIQUE INDEX IF NOT EXISTS uq_establishment_ukprn
    ON core.establishment (ukprn)
    WHERE ukprn IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_establishment_diocese'
          AND conrelid = 'core.establishment'::regclass
    ) THEN
        ALTER TABLE core.establishment
            ADD CONSTRAINT fk_establishment_diocese
            FOREIGN KEY (diocese_id) REFERENCES ref.diocese (diocese_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_establishment_diocese_id
    ON core.establishment (diocese_id);

-- Effective-dated diocese history. The establishment.diocese_id column is
-- the convenient current value for v0.1; application/service logic must
-- update it in the same transaction as this history.
CREATE TABLE IF NOT EXISTS core.establishment_diocese_history (
    establishment_diocese_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL,
    diocese_id BIGINT NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source TEXT,
    CONSTRAINT fk_establishment_diocese_history_establishment
        FOREIGN KEY (establishment_id) REFERENCES core.establishment (establishment_id) ON DELETE CASCADE,
    CONSTRAINT fk_establishment_diocese_history_diocese
        FOREIGN KEY (diocese_id) REFERENCES ref.diocese (diocese_id),
    CONSTRAINT chk_establishment_diocese_history_dates
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT uq_establishment_diocese_history_start
        UNIQUE (establishment_id, effective_from)
);

CREATE INDEX IF NOT EXISTS idx_establishment_diocese_history_establishment
    ON core.establishment_diocese_history (establishment_id, effective_from, effective_to);

-- Only one open-ended/current history row per establishment.
CREATE UNIQUE INDEX IF NOT EXISTS uq_establishment_diocese_history_current
    ON core.establishment_diocese_history (establishment_id)
    WHERE effective_to IS NULL;

-- ------------------------------------------------------------
-- 4. Local authority reference and effective-dated relationship
-- ------------------------------------------------------------

-- Retain legacy authority_code/authority_name columns during v0.1 migration,
-- but add the normalized FK and dating columns. The relationship is intended
-- to become the source of truth; a current view is provided below.
ALTER TABLE core.establishment_authority
    ADD COLUMN IF NOT EXISTS local_authority_id BIGINT,
    ADD COLUMN IF NOT EXISTS relationship_type TEXT,
    ADD COLUMN IF NOT EXISTS effective_from DATE,
    ADD COLUMN IF NOT EXISTS effective_to DATE,
    ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS source TEXT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_establishment_authority_local_authority'
          AND conrelid = 'core.establishment_authority'::regclass
    ) THEN
        ALTER TABLE core.establishment_authority
            ADD CONSTRAINT fk_establishment_authority_local_authority
            FOREIGN KEY (local_authority_id) REFERENCES ref.local_authority (local_authority_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_establishment_authority_dates'
          AND conrelid = 'core.establishment_authority'::regclass
    ) THEN
        ALTER TABLE core.establishment_authority
            ADD CONSTRAINT chk_establishment_authority_dates
            CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_establishment_authority_establishment_dates
    ON core.establishment_authority (establishment_id, effective_from, effective_to);

CREATE INDEX IF NOT EXISTS idx_establishment_authority_local_authority
    ON core.establishment_authority (local_authority_id);

-- One open-ended relationship of each type per establishment.
CREATE UNIQUE INDEX IF NOT EXISTS uq_establishment_authority_current_type
    ON core.establishment_authority (establishment_id, COALESCE(relationship_type, 'RESPONSIBLE'))
    WHERE effective_to IS NULL AND local_authority_id IS NOT NULL;

-- ------------------------------------------------------------
-- 5. Admissions gender
-- ------------------------------------------------------------

ALTER TABLE core.establishment_admissions
    ADD COLUMN IF NOT EXISTS admissions_gender_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_establishment_admissions_gender'
          AND conrelid = 'core.establishment_admissions'::regclass
    ) THEN
        ALTER TABLE core.establishment_admissions
            ADD CONSTRAINT fk_establishment_admissions_gender
            FOREIGN KEY (admissions_gender_id)
            REFERENCES ref.admissions_gender (admissions_gender_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_establishment_admissions_gender
    ON core.establishment_admissions (admissions_gender_id);

-- ------------------------------------------------------------
-- 6. Religious character and ethos
-- ------------------------------------------------------------

ALTER TABLE core.establishment_religion
    ADD COLUMN IF NOT EXISTS religious_character_id BIGINT,
    ADD COLUMN IF NOT EXISTS religious_ethos_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_establishment_religion_character'
          AND conrelid = 'core.establishment_religion'::regclass
    ) THEN
        ALTER TABLE core.establishment_religion
            ADD CONSTRAINT fk_establishment_religion_character
            FOREIGN KEY (religious_character_id)
            REFERENCES ref.religious_character (religious_character_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_establishment_religion_ethos'
          AND conrelid = 'core.establishment_religion'::regclass
    ) THEN
        ALTER TABLE core.establishment_religion
            ADD CONSTRAINT fk_establishment_religion_ethos
            FOREIGN KEY (religious_ethos_id)
            REFERENCES ref.religious_ethos (religious_ethos_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_establishment_religion_character
    ON core.establishment_religion (religious_character_id);
CREATE INDEX IF NOT EXISTS idx_establishment_religion_ethos
    ON core.establishment_religion (religious_ethos_id);

-- Existing religious_character and religious_ethos text columns are retained
-- temporarily to support migration/reconciliation.

-- ------------------------------------------------------------
-- 7. Nursery provision: complete missing FK
-- ------------------------------------------------------------

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_establishment_provision_nursery_provision'
          AND conrelid = 'core.establishment_provision'::regclass
    ) THEN
        ALTER TABLE core.establishment_provision
            ADD CONSTRAINT fk_establishment_provision_nursery_provision
            FOREIGN KEY (nursery_provision_id)
            REFERENCES ref.nursery_provision (nursery_provision_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_establishment_provision_nursery
    ON core.establishment_provision (nursery_provision_id);

-- ------------------------------------------------------------
-- 8. Boarding provision and boarding-establishment type
-- ------------------------------------------------------------

ALTER TABLE core.establishment_boarding
    ADD COLUMN IF NOT EXISTS boarders_id BIGINT,
    ADD COLUMN IF NOT EXISTS boarding_establishment_type_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_establishment_boarding_boarders'
          AND conrelid = 'core.establishment_boarding'::regclass
    ) THEN
        ALTER TABLE core.establishment_boarding
            ADD CONSTRAINT fk_establishment_boarding_boarders
            FOREIGN KEY (boarders_id) REFERENCES ref.boarders (boarders_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_establishment_boarding_type'
          AND conrelid = 'core.establishment_boarding'::regclass
    ) THEN
        ALTER TABLE core.establishment_boarding
            ADD CONSTRAINT fk_establishment_boarding_type
            FOREIGN KEY (boarding_establishment_type_id)
            REFERENCES ref.boarding_establishment_type (boarding_establishment_type_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_establishment_boarding_boarders
    ON core.establishment_boarding (boarders_id);
CREATE INDEX IF NOT EXISTS idx_establishment_boarding_type
    ON core.establishment_boarding (boarding_establishment_type_id);

-- Existing boarding_provision text is retained temporarily for reconciliation.

-- ------------------------------------------------------------
-- 9. SEN classifications
-- ------------------------------------------------------------

ALTER TABLE core.establishment_sen
    ADD COLUMN IF NOT EXISTS section41_approval_status_id BIGINT,
    ADD COLUMN IF NOT EXISTS special_classes_id BIGINT,
    ADD COLUMN IF NOT EXISTS type_of_resourced_provision_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_establishment_sen_section41_status'
          AND conrelid = 'core.establishment_sen'::regclass
    ) THEN
        ALTER TABLE core.establishment_sen
            ADD CONSTRAINT fk_establishment_sen_section41_status
            FOREIGN KEY (section41_approval_status_id)
            REFERENCES ref.section41_approval_status (section41_approval_status_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_establishment_sen_special_classes'
          AND conrelid = 'core.establishment_sen'::regclass
    ) THEN
        ALTER TABLE core.establishment_sen
            ADD CONSTRAINT fk_establishment_sen_special_classes
            FOREIGN KEY (special_classes_id)
            REFERENCES ref.special_classes (special_classes_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_establishment_sen_resourced_provision_type'
          AND conrelid = 'core.establishment_sen'::regclass
    ) THEN
        ALTER TABLE core.establishment_sen
            ADD CONSTRAINT fk_establishment_sen_resourced_provision_type
            FOREIGN KEY (type_of_resourced_provision_id)
            REFERENCES ref.type_of_resourced_provision (type_of_resourced_provision_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_establishment_sen_section41
    ON core.establishment_sen (section41_approval_status_id);
CREATE INDEX IF NOT EXISTS idx_establishment_sen_special_classes
    ON core.establishment_sen (special_classes_id);
CREATE INDEX IF NOT EXISTS idx_establishment_sen_resourced_provision_type
    ON core.establishment_sen (type_of_resourced_provision_id);

-- ------------------------------------------------------------
-- 10. Dated provision observations
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS core.establishment_provision_observation (
    establishment_provision_observation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    establishment_id BIGINT NOT NULL,
    provision_measure_type_id BIGINT NOT NULL,
    observation_date DATE NOT NULL,
    value NUMERIC(12,2) NOT NULL,
    source TEXT,
    source_reference TEXT,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_provision_observation_establishment
        FOREIGN KEY (establishment_id)
        REFERENCES core.establishment (establishment_id) ON DELETE CASCADE,
    CONSTRAINT fk_provision_observation_measure_type
        FOREIGN KEY (provision_measure_type_id)
        REFERENCES ref.provision_measure_type (provision_measure_type_id),
    CONSTRAINT chk_provision_observation_nonnegative
        CHECK (value >= 0),
    CONSTRAINT uq_provision_observation
        UNIQUE (establishment_id, provision_measure_type_id, observation_date, source)
);

CREATE INDEX IF NOT EXISTS idx_provision_observation_establishment_date
    ON core.establishment_provision_observation (establishment_id, observation_date DESC);
CREATE INDEX IF NOT EXISTS idx_provision_observation_measure_date
    ON core.establishment_provision_observation (provision_measure_type_id, observation_date DESC);

-- ------------------------------------------------------------
-- 11. Current-state views
-- ------------------------------------------------------------

CREATE OR REPLACE VIEW core.current_establishment_local_authority AS
SELECT DISTINCT ON (ea.establishment_id)
    ea.establishment_id,
    ea.establishment_authority_id,
    ea.local_authority_id,
    la.code AS local_authority_code,
    la.name AS local_authority_name,
    ea.relationship_type,
    ea.effective_from,
    ea.effective_to
FROM core.establishment_authority ea
JOIN ref.local_authority la
  ON la.local_authority_id = ea.local_authority_id
WHERE (ea.effective_from IS NULL OR ea.effective_from <= CURRENT_DATE)
  AND (ea.effective_to IS NULL OR ea.effective_to > CURRENT_DATE)
ORDER BY ea.establishment_id, ea.effective_from DESC NULLS LAST,
         ea.establishment_authority_id DESC;

CREATE OR REPLACE VIEW core.establishment_lifecycle_dates AS
SELECT
    e.establishment_id,
    MIN(le.event_date) FILTER (
        WHERE LOWER(le.event_type) IN ('open', 'opened', 'opening')
    ) AS open_date,
    MAX(le.event_date) FILTER (
        WHERE LOWER(le.event_type) IN ('close', 'closed', 'closing')
    ) AS close_date
FROM core.establishment e
LEFT JOIN core.establishment_lifecycle_event le
  ON le.establishment_id = e.establishment_id
GROUP BY e.establishment_id;

COMMIT;

-- ============================================================
-- Deferred from v0.1
-- ============================================================
-- * Legacy lookup seed rows other than Section 41.
-- * Religion wording and diocese-to-religion mapping confirmation.
-- * FSM measure definition and denominator.
-- * Exclusion constraints preventing all effective-date overlaps.
-- * Automated synchronization of establishment.diocese_id with history.
-- * Removal of legacy free-text columns after reconciliation.
-- ============================================================
